USE if0_41928864_encyclawphilia_db;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `Comment_Reactions`;
TRUNCATE TABLE `Ordinance_Reactions`;
TRUNCATE TABLE `Comments`;
TRUNCATE TABLE `Ordinance_Tags`;
TRUNCATE TABLE `Tags`;
TRUNCATE TABLE `Ordinances`;
TRUNCATE TABLE `Categories`;
TRUNCATE TABLE `Barangays`;
TRUNCATE TABLE `Users`;
TRUNCATE TABLE `Roles`;

SET FOREIGN_KEY_CHECKS = 1;
